language: python

sudo: true

addons:
    apt_packages:
        - liblapack-dev
        - libblas-dev
        - libboost-dev
        - libarmadillo-dev

python:
    - 2.7
    - 3.3
    - 3.4

install:
    - python setup.py install

script:
    - cd ids_teach/tests && py.test
